apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: mnist
  namespace: openfaas-fn
spec:
  name: mnist
  image: danisimov84/mnist:latest-e2c45f6
  environment:
    batch_size: "128"
    exec_timeout: 20m
    read_timeout: 1m
    write_debug: "true"
    write_timeout: 1m
