name: MNIST-CI

on: 
  push:
    paths:
      - 'mnist/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: checkout
        uses: actions/checkout@v1
                  
      - name: d login
        if: "success() && github.ref == 'refs/heads/master' "
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Declare SHA vars to use on other actions
        id: vars
        shell: bash
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: OpenFaaS build and push
        uses: mrsimpson/action-openfaas-build@master
        with:
          stack-file: mnist.yml
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64
          tag: latest-${{ steps.vars.outputs.sha_short }}

      - name: update current version
        uses: mikefarah/yq@3.3.2
        if: "success() && github.ref == 'refs/heads/master' "
        with: 
          cmd: yq w -i mnist/mnist.yaml spec.image "danisimov84/mnist:latest-${{ steps.vars.outputs.sha_short }}"