name: MNIST-CI

on: 
  push:
    paths:
      - 'mnist/*'
      - '.github/workflows/mnist-wfl.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: checkout
        uses: actions/checkout@v1
                  
      - name: d login
        if: "success() && github.ref == 'refs/heads/master' "
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Declare SHA vars to use on other actions
        id: vars
        shell: bash
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: update current version
        uses: mikefarah/yq@3.3.2
        if: "success() && github.ref == 'refs/heads/master' "
        with: 
          cmd: yq w -i mnist/mnist.yaml spec.image "danisimov84/mnist:latest-${{ steps.vars.outputs.sha_short }}" && \
            yq w -i mnist.yml functions.mnist.image "danisimov84/mnist:latest-${{ steps.vars.outputs.sha_short }}"

      - name: OpenFaaS build and push
        uses: mrsimpson/action-openfaas-build@0.3.0     
        with:
          stack-file: mnist.yml
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64

      - name: setup git config
        if: "success() && github.ref == 'refs/heads/master' "
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add mnist/mnist.yaml mnist.yml
          git commit -m "update version to ${{ steps.vars.outputs.sha_short }}"
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master